languageCode: en-us
baseurl: "https://drizuid.github.io"
title: longoconsulting.us
theme: ["PaperMod"]
paginate: 10

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

params:
  author: Will
  defaultTheme: auto
  title: longoconsulting.us
  description: My adventures and misadventures in IT
  keywords: [Blog, Hugo, PaperMod]
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true

  homeInfoParams:
    Title: My IT Adventures!
    Content: |
      Hey, I'm one of the linuxserver.io teammembers and enjoy technology! Professionally, I'm an IT consultant with a focus on cisco route/switch and collaboration, but I am also someone who dabbles in everything IT. 

      I've been a Linux user since '96, an Asterisk user since '02, a Cisco route/switch guy since 2000 and various other things along the way. 

      I'm a former US Army officer, I spent 11 years in the military and deployed to Afghanistan multiple times. As a Functional Area 24 officer, I got to do some pretty interesting stuff and thoroughly enjoyed my time in the service. 

      I have various degrees ranging from associates to doctoral with some being still-in-progress-never-to-be-completed and numerous IT related certifications. 
      
      If you enjoy my blog, please consider sending me a donation! I enjoy bitcoin, ethereum, and long walks on the beach. 
  socialIcons:
  - name: mastodon
    url: "https://mastodon.linuxserver.io/@driz"
  - name: github
    url: "https://github.com/drizuid"
  - name: discord
    url: "https://discord.gg/linuxserver"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: search
      name: search
      url: /search/
      weight: 20
    - identifier: archives
      name: archives
      url: /archives/
      weight: 30

pygmentsUseClasses: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    noClasses: false
    style: onedark

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
